---

- name: install aptly-api
  apt:
    name: aptly-api
    default_release: stretch-backports
    state: latest

- name: install /etc/default/aptly-api
  template:
    src: aptly-api.default
    dest: /etc/default/aptly-api
  notify:
    - restart aptly-api

- name: enable and start the aptly-api service
  service:
    name: aptly-api
    state: started
    enabled: yes
