---

- name: install nginx
  apt:
    name: nginx
    state: latest

- name: enable the nginx service
  service:
    name: nginx
    enabled: yes

- name: configure nginx
  template:
    src: nginx-default
    dest: /etc/nginx/sites-enabled/default
  notify:
    - restart nginx

- name: install the autodeb-server deb
  apt:
    deb: https://autodeb-team.pages.debian.net/autodeb-packaging/autodeb-server_latest.deb
  notify:
    - restart autodeb-server

- name: enable and start the autodeb-server service
  service:
    name: autodeb-server
    state: started
    enabled: yes
