---

- name: postgres container
  docker_container:
    name: postgres
    image: postgres
    state: absent

- name: purge autodeb-server
  apt:
    name: autodeb-server
    state: absent
    purge: yes

- name: purge autodeb-worker
  apt:
    name: autodeb-worker
    state: absent
    purge: yes

- name: purge chroots
  command: "{{ item }}"
  with_items:
    - bash -c "rm -rf /srv/chroot/*"
    - bash -c "rm -rf /etc/schroot/chroot.d/*"
