---

- name: postgres container
  docker_container:
    name: postgres
    image: postgres
    state: absent

- name: purge autodeb-server
  apt:
    name: autodeb-server
    state: absent
    purge: yes

- name: purge autodeb-worker
  apt:
    name: autodeb-worker
    state: absent
    purge: yes

- name: end all schroot sessions
  command: schroot --all --end-session --force
  ignore_errors: yes

- name: purge the schroot package
  apt:
    name: schroot
    state: absent
    purge: yes

- name: purge chroots
  command: "{{ item }}"
  with_items:
    - bash -c "rm -rf /srv/chroot/*"
    - bash -c "rm -rf /etc/schroot/chroot.d/*"
    - bash -c "rm -rf /var/lib/schroot/*"

- name: purge aptly repositories
  file:
    state: absent
    path: /var/lib/aptly-api

- name: purge aptly-api
  apt:
    name: aptly-api
    state: absent
    purge: yes
