---

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Install python-docker
  apt:
    name: python-docker
    state: present
    update_cache: yes

- name: Install Docker repo keys
  apt_key:
    keyserver: pgp.mit.edu
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Enable Docker repositories
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian stretch stable"
    state: present
    update_cache: yes

- name: Install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes