---

- name: install debian backports
  apt_repository:
    repo: deb http://ftp.debian.org/debian stretch-backports main
    state: present

- name: update all packages to the latest version
  apt:
    upgrade: dist

- include: common_packages.yml
- include: authorized_keys.yml
